#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("com.flaxtreme.CT.Resource", IsApplication=true)]

namespace com.flaxtreme.CT
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int play_store_icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int share = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int vk = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000e
			public const int AnnoText = 2131034126;
			
			// aapt resource value: 0x7f05000a
			public const int AppName = 2131034122;
			
			// aapt resource value: 0x7f05000c
			public const int MathButton = 2131034124;
			
			// aapt resource value: 0x7f05000f
			public const int StartButton = 2131034127;
			
			// aapt resource value: 0x7f050011
			public const int linearLayout1 = 2131034129;
			
			// aapt resource value: 0x7f050002
			public const int marketButton = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int marketTextView = 2131034115;
			
			// aapt resource value: 0x7f050019
			public const int nextButton = 2131034137;
			
			// aapt resource value: 0x7f050018
			public const int passButton = 2131034136;
			
			// aapt resource value: 0x7f050017
			public const int prevButton = 2131034135;
			
			// aapt resource value: 0x7f050001
			public const int relativeLayout1 = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int relativeLayout2 = 2131034116;
			
			// aapt resource value: 0x7f050007
			public const int relativeLayout3 = 2131034119;
			
			// aapt resource value: 0x7f050010
			public const int scrollView1 = 2131034128;
			
			// aapt resource value: 0x7f050008
			public const int shareButton = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int shareTextView = 2131034121;
			
			// aapt resource value: 0x7f050012
			public const int subjectNameLabel = 2131034130;
			
			// aapt resource value: 0x7f050015
			public const int taskImage = 2131034133;
			
			// aapt resource value: 0x7f050014
			public const int taskLabel = 2131034132;
			
			// aapt resource value: 0x7f050013
			public const int taskNameLabel = 2131034131;
			
			// aapt resource value: 0x7f050000
			public const int testResultTextView = 2131034112;
			
			// aapt resource value: 0x7f05000b
			public const int textView1 = 2131034123;
			
			// aapt resource value: 0x7f05000d
			public const int textView2 = 2131034125;
			
			// aapt resource value: 0x7f050016
			public const int variantsLayout = 2131034134;
			
			// aapt resource value: 0x7f050005
			public const int vkButton = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int vkTextView = 2131034118;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int FinishTest = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int PreTest = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int TestTask = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int BelButton = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int MathButton = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int RussianButton = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int SettingsButton = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int app_name = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int descr_text = 2130968581;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
