#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("com.flaxtreme.CT.Resource", IsApplication=true)]

namespace com.flaxtreme.CT
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int play_store_icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int share = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int splash = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int vk = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060010
			public const int AnnoText = 2131099664;
			
			// aapt resource value: 0x7f06000b
			public const int AppName = 2131099659;
			
			// aapt resource value: 0x7f06000e
			public const int BelButton = 2131099662;
			
			// aapt resource value: 0x7f06000c
			public const int MathButton = 2131099660;
			
			// aapt resource value: 0x7f06000f
			public const int PhysButton = 2131099663;
			
			// aapt resource value: 0x7f06000d
			public const int RusButton = 2131099661;
			
			// aapt resource value: 0x7f060011
			public const int StartButton = 2131099665;
			
			// aapt resource value: 0x7f060013
			public const int linearLayout1 = 2131099667;
			
			// aapt resource value: 0x7f060002
			public const int marketButton = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int marketTextView = 2131099651;
			
			// aapt resource value: 0x7f06001b
			public const int nextButton = 2131099675;
			
			// aapt resource value: 0x7f06001a
			public const int passButton = 2131099674;
			
			// aapt resource value: 0x7f060019
			public const int prevButton = 2131099673;
			
			// aapt resource value: 0x7f060001
			public const int relativeLayout1 = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int relativeLayout2 = 2131099652;
			
			// aapt resource value: 0x7f060007
			public const int relativeLayout3 = 2131099655;
			
			// aapt resource value: 0x7f060012
			public const int scrollView1 = 2131099666;
			
			// aapt resource value: 0x7f060008
			public const int shareButton = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int shareTextView = 2131099657;
			
			// aapt resource value: 0x7f060014
			public const int subjectNameLabel = 2131099668;
			
			// aapt resource value: 0x7f060017
			public const int taskImage = 2131099671;
			
			// aapt resource value: 0x7f060016
			public const int taskLabel = 2131099670;
			
			// aapt resource value: 0x7f060015
			public const int taskNameLabel = 2131099669;
			
			// aapt resource value: 0x7f060000
			public const int testResultTextView = 2131099648;
			
			// aapt resource value: 0x7f06000a
			public const int textView2 = 2131099658;
			
			// aapt resource value: 0x7f060018
			public const int variantsLayout = 2131099672;
			
			// aapt resource value: 0x7f060005
			public const int vkButton = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int vkTextView = 2131099654;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int FinishTest = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int PreTest = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int TestTask = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int BelButton = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int MathButton = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int PhysButton = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int RusButton = 2130968577;
			
			// aapt resource value: 0x7f040004
			public const int SettingsButton = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int app_name = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int descr_text = 2130968582;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
