#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("com.flaxtreme.CT.Resource", IsApplication=true)]

namespace com.flaxtreme.CT
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int border = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int play_store_icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int share = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int splash = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int vk = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060016
			public const int AnnoText = 2131099670;
			
			// aapt resource value: 0x7f06002d
			public const int AnswerTextBox = 2131099693;
			
			// aapt resource value: 0x7f060011
			public const int AppName = 2131099665;
			
			// aapt resource value: 0x7f060014
			public const int BelButton = 2131099668;
			
			// aapt resource value: 0x7f060025
			public const int MainLayout = 2131099685;
			
			// aapt resource value: 0x7f060012
			public const int MathButton = 2131099666;
			
			// aapt resource value: 0x7f060029
			public const int NextButton = 2131099689;
			
			// aapt resource value: 0x7f060032
			public const int PastTask = 2131099698;
			
			// aapt resource value: 0x7f060015
			public const int PhysButton = 2131099669;
			
			// aapt resource value: 0x7f060027
			public const int PrevButton = 2131099687;
			
			// aapt resource value: 0x7f060013
			public const int RusButton = 2131099667;
			
			// aapt resource value: 0x7f060030
			public const int SolutionImage = 2131099696;
			
			// aapt resource value: 0x7f060031
			public const int SolutionInetLink = 2131099697;
			
			// aapt resource value: 0x7f06002f
			public const int SolutionText = 2131099695;
			
			// aapt resource value: 0x7f060017
			public const int StartButton = 2131099671;
			
			// aapt resource value: 0x7f060001
			public const int SubjectNameTextView = 2131099649;
			
			// aapt resource value: 0x7f06002b
			public const int TaskImage = 2131099691;
			
			// aapt resource value: 0x7f060028
			public const int TaskName = 2131099688;
			
			// aapt resource value: 0x7f06002a
			public const int TaskText = 2131099690;
			
			// aapt resource value: 0x7f060006
			public const int TasksLinearLayout = 2131099654;
			
			// aapt resource value: 0x7f060019
			public const int TestButton = 2131099673;
			
			// aapt resource value: 0x7f060005
			public const int ThemeName = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int ThemesLinearLayout = 2131099652;
			
			// aapt resource value: 0x7f060018
			public const int TraningButton = 2131099672;
			
			// aapt resource value: 0x7f06002c
			public const int VariantsGroup = 2131099692;
			
			// aapt resource value: 0x7f060000
			public const int linearLayout1 = 2131099648;
			
			// aapt resource value: 0x7f06001a
			public const int linearLayout2 = 2131099674;
			
			// aapt resource value: 0x7f06002e
			public const int linearLayout3 = 2131099694;
			
			// aapt resource value: 0x7f060026
			public const int linearLayout4 = 2131099686;
			
			// aapt resource value: 0x7f060009
			public const int marketButton = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int marketTextView = 2131099658;
			
			// aapt resource value: 0x7f060024
			public const int nextButton = 2131099684;
			
			// aapt resource value: 0x7f060023
			public const int passButton = 2131099683;
			
			// aapt resource value: 0x7f060022
			public const int prevButton = 2131099682;
			
			// aapt resource value: 0x7f060008
			public const int relativeLayout1 = 2131099656;
			
			// aapt resource value: 0x7f06000b
			public const int relativeLayout2 = 2131099659;
			
			// aapt resource value: 0x7f06000e
			public const int relativeLayout3 = 2131099662;
			
			// aapt resource value: 0x7f060003
			public const int scrollView1 = 2131099651;
			
			// aapt resource value: 0x7f06000f
			public const int shareButton = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int shareTextView = 2131099664;
			
			// aapt resource value: 0x7f06001d
			public const int subjectNameLabel = 2131099677;
			
			// aapt resource value: 0x7f060020
			public const int taskImage = 2131099680;
			
			// aapt resource value: 0x7f06001f
			public const int taskLabel = 2131099679;
			
			// aapt resource value: 0x7f06001e
			public const int taskNameLabel = 2131099678;
			
			// aapt resource value: 0x7f060007
			public const int testResultTextView = 2131099655;
			
			// aapt resource value: 0x7f06001b
			public const int textView1 = 2131099675;
			
			// aapt resource value: 0x7f060002
			public const int textView2 = 2131099650;
			
			// aapt resource value: 0x7f06001c
			public const int traningButton = 2131099676;
			
			// aapt resource value: 0x7f060021
			public const int variantsLayout = 2131099681;
			
			// aapt resource value: 0x7f06000c
			public const int vkButton = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int vkTextView = 2131099661;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ChooseTrainingLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ChooseTrainingTasksLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int FinishTest = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int PreTest = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int SubjectActivity = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int SubjectLayout = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int TestTask = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int TrainingTasksLayout = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int Belarussian = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int Math = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int Physics = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int Russian = 2130968577;
			
			// aapt resource value: 0x7f040004
			public const int SettingsButton = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int app_name = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int descr_text = 2130968582;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Theme_Splash = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int VariantButton = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int VariantButton_Checked = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int VariantButton_Right = 2131034117;
			
			// aapt resource value: 0x7f050002
			public const int VariantButton_Standart = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int VariantButton_Wrong = 2131034116;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
